name: Build Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Read Tag Version
      id: version
      run: echo version=$(echo "${{ github.event.ref }}" | cut -d'/' -f3 | cut -c2-) >> $GITHUB_OUTPUT

    - name: Get Repository Name in Lowercase
      id: name
      run: echo image_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]') >> $GITHUB_OUTPUT
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ steps.name.outputs.image_name }}
        tags: |
          ${{ steps.version.outputs.version }}
          latest
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Release
      uses: softprops/action-gh-release@v2
