# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Application

on:
  workflow_dispatch:
    inputs:
      shutdown_key:
        description: 'shutdown key'
        required: true
        type: string
      
permissions:
  contents: read

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Restore Cache Log
      uses: actions/cache@v3
      with:
        path: twitter/*/*.log
        key: log-cache-${{ github.run_number }}
        restore-keys: |
          log-cache-
    - name: Run Application
      run: |
        pip3 install -r requirements.txt && sudo apt update && sudo apt install libimage-exiftool-perl -y
        sed -i 's/"save_path": ""/"save_path": "twitter"/' settings.json
        sed -i 's/"down_log": false/"down_log": true/' settings.json
        sed -i 's/"autoSync": false/"autoSync": true/' settings.json
        sed -i 's/auth_token=xxxxxxxxxxx; ct0=xxxxxxxxxxx;/${{ secrets.cookie }}/' settings.json
        python3 main.py
    - name: Copy File
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.KEY }}
        source: "twitter,!twitter/*/*.csv"
        target: /twitter
    - name: Shutdown Server
      if: ${{ github.event.inputs.shutdown_key != '' }}
      run: |
        curl ${{ secrets.HOST }}:${{ secrets.WEB_PORT }}?shutdownKey=${{ github.event.inputs.shutdown_key }}
